services:
  - type: web
    name: skolanalys-api
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: education_department_data
          property: connectionString
      - key: SYSTEM_PROMPT_PATH
        value: system_prompt.txt
      - key: EMBED_DIM
        value: "768"
      - key: PYTHON_VERSION
        value: "3.12"

databases:
  - name: education_department_data
    databaseName: education_department_data
    user: postgres
    region: frankfurt
    plan: starter
    postgresSQLVersion: "18"
